-- Carga unica: itens do cupom (Casas Guanabara) no estoque da familia Brasiliense.
-- Reusa mercado_apply_purchase_h (0014): cria/soma produto, grava a compra,
-- ajusta par_level e baixa itens pendentes da lista. Nomes normalizados de fiscal
-- -> generico + marca; qtd e preco unitario vem direto da nota.
-- Rode no SQL Editor do Supabase. Se rodar 2x, o estoque SOMA de novo (nao ha dedup).

do $$
declare
  h uuid;
  r record;
  n int := 0;
begin
  select id into h from households where lower(name) like '%brasiliense%' limit 1;
  if h is null then
    raise exception 'familia Brasiliense nao encontrada em households.name';
  end if;

  for r in
    select * from (values
      ('salsicha',                 'perdigao',    0.988,   9.98, 'kg'),
      ('bisteca suina',            'sadia',       2,      11.98, 'un'),
      ('brocolis congelado',       'lar',         2,      13.98, 'un'),
      ('kani kama',                'costa sul',   1,       8.98, 'un'),
      ('morango congelado',        'easychef',    1,      15.98, 'un'),
      ('batata congelada',         'easychef',    1,      17.75, 'un'),
      ('file de panga',            'bom pesca',   3,      19.98, 'un'),
      ('waffle',                   'waaw',        1,       9.35, 'un'),
      ('hamburguer bovino',        'friboi',      1,       6.98, 'un'),
      ('linguica calabresa',       'seara',       1.008,  19.98, 'kg'),
      ('lasanha',                  'forno de minas', 1,    9.98, 'un'),
      ('peito de frango moido',    'copacol',     1,       9.98, 'un'),
      ('sobrecoxa de frango',      'swift',       1,      13.90, 'un'),
      ('bacon de lombo',           'pata negra',  0.406,  50.00, 'kg'),
      ('margarina',                'qualy',       2,       8.99, 'un'),
      ('file de peito de frango',  'lar',         5,      15.47, 'kg'),
      ('presunto cozido',          'seara',       0.22,   32.91, 'kg'),
      ('queijo mucarela',          'domilac',     0.408,  56.99, 'kg'),
      ('queijo polenguinho',       'polenghi',    1,       9.98, 'un'),
      ('ricota fresca',            'dumont',      0.334,  25.00, 'kg'),
      ('leite integral',           'piracanjuba', 12,      5.49, 'un'),
      ('leite fermentado activia', 'activia',     1,      14.08, 'un'),
      ('iogurte',                  'nestle',      1,      12.49, 'un'),
      ('queijo processado',        'supremo',     1,      12.77, 'un'),
      ('sobrecoxa de frango',      'swift',       1,      19.90, 'un'),
      ('bisnaguinho',              'plus vita',   3,       6.99, 'un'),
      ('pao de hamburguer',        'plus vita',   1,      13.99, 'un'),
      ('farinha neston',           'neston',      1,       5.99, 'un'),
      ('pao de forma',             'q-pao',       3,       4.95, 'un'),
      ('cafe',                     '3 coracoes',  1,      27.90, 'un'),
      ('salgadinho skiny',         'skiny',       3,       3.68, 'un'),
      ('biscoito wafer',           'piraque',     4,       2.98, 'un'),
      ('biscoito wafer',           'piraque',     3,       2.98, 'un'),
      ('salgadinho skiny',         'skiny',       2,       3.48, 'un'),
      ('pacoca',                   'santa helena',1,      13.80, 'un'),
      ('salgadinho fofura',        'elma chips',  2,       1.69, 'un'),
      ('milho de pipoca',          'yoki',        3,       3.69, 'un'),
      ('feijao preto',             'kicaldo',     1,       5.99, 'un'),
      ('farinha de trigo',         'boa sorte',   1,       3.89, 'un'),
      ('acucar refinado',          'uniao',       1,       3.19, 'un'),
      ('farinha de mandioca',      'tipity',      2,       4.56, 'un'),
      ('farofa',                   'yoki',        1,       4.89, 'un'),
      ('acucar demerara',          'uniao',       1,       5.49, 'un'),
      ('queijo parmesao',          'quata',       0.144, 138.49, 'kg'),
      ('sal refinado',             'ita',         1,       2.69, 'un'),
      ('farofa',                   'yoki',        1,       4.89, 'un'),
      ('biscoito',                 'adria',       4,       3.29, 'un'),
      ('arroz',                    'combrasil',   1,      18.95, 'un'),
      ('biscoito oreo',            'oreo',        1,       3.39, 'un'),
      ('cookie',                   'piraque',     4,       3.79, 'un'),
      ('macarrao instantaneo',     'nissin',      1,      16.14, 'un'),
      ('salgadinho torcida',       'torcida',     2,       1.65, 'un'),
      ('salgadinho skiny',         'skiny',       2,       3.48, 'un'),
      ('macarrao instantaneo',     'nissin',      1,       3.10, 'un'),
      ('biscoito trakinas',        'trakinas',    1,       2.79, 'un'),
      ('salgadinho torcida',       'torcida',     1,       1.65, 'un'),
      ('batata chips',             'lays',        1,      18.90, 'un'),
      ('batata palha',             'crac',        1,      16.19, 'un'),
      ('alga marinha yakinori',    '',            1,      33.96, 'un'),
      ('macarrao instantaneo',     'nissin',      1,       3.28, 'un'),
      ('biscoito trakinas',        'trakinas',    1,       2.79, 'un'),
      ('limao',                    '',            0.568,   4.99, 'kg'),
      ('cebola',                   '',            2.543,   7.35, 'kg'),
      ('mamao',                    '',            0.933,   9.35, 'kg'),
      ('berinjela',                '',            0.518,   7.33, 'kg'),
      ('cenoura',                  '',            0.338,   8.95, 'kg'),
      ('batata',                   '',            2.348,   7.35, 'kg'),
      ('alho',                     '',            0.198,  19.98, 'kg'),
      ('tomate',                   '',            0.923,   9.35, 'kg'),
      ('ameixa',                   '',            0.288,  38.60, 'kg'),
      ('gengibre',                 '',            0.053,  10.65, 'kg'),
      ('palmito',                  'golden palm', 1,      16.98, 'un'),
      ('sardinha',                 'gomes da costa', 3,    5.75, 'un'),
      ('sardinha',                 'gomes da costa', 1,    5.75, 'un'),
      ('caldo de carne',           'knorr',       1,       4.29, 'un'),
      ('tempero',                  'sazon',       1,       4.79, 'un'),
      ('milho verde',             'pramesa',      5,       2.79, 'un'),
      ('caldo de galinha',         'knorr',       1,       3.99, 'un'),
      ('goiabada',                 'predilecta',  1,       7.45, 'un'),
      ('creme de leite',           'italac',      8,       1.99, 'un'),
      ('vinagre de arroz',         'kenko',       1,       7.98, 'un'),
      ('atum',                     'pescador',    3,       7.98, 'un'),
      ('chocolate snickers',       'snickers',    1,       7.75, 'un'),
      ('cha preto',                'lipton',      1,       6.99, 'un'),
      ('vinho cabernet sauvignon', '',            1,      22.45, 'un'),
      ('geleia de amora',          'ritter',      1,      21.39, 'un'),
      ('molho teriyaki',           'sakura',      1,       9.89, 'un'),
      ('suco concentrado de caju', 'dafruta',     1,       3.49, 'un'),
      ('maionese',                 'hellmanns',   1,      22.15, 'un'),
      ('xarope de acai',           'acaicamp',    2,      11.79, 'un'),
      ('vinho tinto',              'les dunes',   1,      29.20, 'un'),
      ('ketchup',                  'cepera',      1,       9.98, 'un'),
      ('tempero',                  'sazon',       1,       4.79, 'un'),
      ('toalha umedecida',         'huggies',     1,       8.99, 'un'),
      ('refrigerante coca-cola',   'coca-cola',   12,      1.99, 'un'),
      ('suco de uva integral',     'campo largo', 1,      15.49, 'un'),
      ('creme dental',             'colgate',     2,       5.40, 'un'),
      ('bloco sanitario',          'hippo',       1,      16.61, 'un'),
      ('alvejante',                'vanish',      1,       6.77, 'un'),
      ('detergente',               'odd',         1,       2.19, 'un'),
      ('difusor de aromas',        'secar',       1,      11.90, 'un'),
      ('detergente',               'odd',         1,       2.19, 'un'),
      ('pedra sanitaria',          'aplik',       2,       2.29, 'un'),
      ('saponaceo',                'cif',         1,      13.99, 'un'),
      ('desodorante',              'rexona',      2,      20.60, 'un'),
      ('amaciante',                'mon bijou',   1,      14.69, 'un'),
      ('desinfetante',             'lysoform',    1,       8.58, 'un'),
      ('sabao pastoso',            'neutral',     1,       8.99, 'un'),
      ('desinfetante',             'pinho sol',   1,       6.71, 'un'),
      ('sabonete',                 'albany',      3,       1.99, 'un'),
      ('sabonete',                 'albany',      1,       1.99, 'un'),
      ('sabonete',                 'francis',     2,       1.99, 'un'),
      ('creme dental',             'colgate',     2,       7.19, 'un'),
      ('papel higienico',          'dualette',    1,      18.98, 'un'),
      ('papel toalha',             'absoluto',    1,       9.70, 'un'),
      ('lava-roupas liquido',      'odd',         1,      20.90, 'un'),
      ('absorvente',               'intimus',     1,      19.17, 'un')
    ) as t(nome, marca, qtd, preco, unidade)
  loop
    perform mercado_apply_purchase_h(h, r.nome, nullif(r.marca,''), r.preco, r.qtd, r.unidade);
    n := n + 1;
  end loop;

  raise notice 'Carga OK: % itens aplicados no estoque da Brasiliense (household %)', n, h;
end $$;
