-- Mercado_app — conserta a ordem do desfazer. Rode DEPOIS de 0023.
--
-- BUG ENCONTRADO NA VERIFICACAO DA 0023, nao pelos self-tests dela:
-- now() em Postgres devolve o horario de INICIO DA TRANSACAO, nao o instante da linha.
-- Duas escritas na mesma transacao gravavam created_at identico, e o
-- "order by created_at desc limit 1" de mercado_desfazer_h escolhia uma delas ao acaso.
-- Reproduzido: "vou_comprar leite" seguido de "tenho leite 3" na mesma transacao, e o
-- desfazer reverteu a inclusao na lista em vez do ajuste de estoque.
--
-- Por que os self-tests da 0023 nao pegaram: cada um deixava apenas UM evento elegivel
-- por vez (os anteriores ja estavam revertidos), entao o empate nunca acontecia.
--
-- Em producao cada mensagem do bot e uma transacao propria, o que mascara o problema.
-- Ele aparece de verdade em: importacao de nota fiscal (mercado_apply_receipt aplica
-- todos os itens numa transacao) e, garantido, no futuro mercado_lote da tarefa C1.
--
-- Correcao: ordem por uma sequencia monotonica, que nao depende de relogio nem de
-- transacao. created_at passa a usar clock_timestamp() (instante real da linha) para o
-- historico ficar honesto, mas quem manda na ordem do desfazer agora e seq.

alter table mercado_events
  add column if not exists seq bigint generated by default as identity;

-- clock_timestamp() avanca dentro da transacao; now() nao.
alter table mercado_events
  alter column created_at set default clock_timestamp();

create index if not exists idx_events_house_seq on mercado_events (household_id, seq desc);

-- Mesma funcao de 0023, com uma unica mudanca: order by seq desc em vez de created_at desc.
create or replace function mercado_desfazer_h(h uuid, p_origem text)
returns json language plpgsql security definer set search_path = public as $$
declare ev record; lids uuid[];
begin
  select * into ev from mercado_events
    where household_id = h and revertido_em is null and acao <> 'desfeito'
    order by seq desc limit 1;
  if not found then
    return json_build_object('ok', false, 'erro', 'nada_para_desfazer');
  end if;
  if ev.created_at < now() - interval '24 hours' then
    return json_build_object('ok', false, 'erro', 'fora_da_janela');
  end if;

  if ev.acao = 'adicionado_lista' then
    update shopping_list set status = 'removed'
      where id = (ev.payload->>'list_id')::uuid and household_id = h;
  else
    if ev.product_id is not null then
      update products set current_stock = ev.antes, updated_at = now()
        where id = ev.product_id and household_id = h;
    end if;
    if jsonb_exists(ev.payload, 'lista_ids') then
      select coalesce(array_agg(x::uuid), '{}'::uuid[]) into lids
        from jsonb_array_elements_text(ev.payload->'lista_ids') x;
      update shopping_list set status = 'pending', bought_at = null
        where id = any(lids) and household_id = h;
    end if;
  end if;

  update mercado_events set revertido_em = now() where id = ev.id;
  perform mercado_log_event(h, ev.product_id, ev.item_name, 'desfeito', ev.depois, ev.antes,
    ev.qtd, p_origem, jsonb_build_object('evento_id', ev.id, 'acao_desfeita', ev.acao));

  return json_build_object('ok', true, 'desfeito', ev.acao, 'item', ev.item_name,
    'antes', ev.depois, 'depois', ev.antes);
end $$;
revoke execute on function mercado_desfazer_h(uuid, text) from public, anon, authenticated, service_role;

-- ============ SELF-TEST: exatamente o cenario que falhou ============
-- Duas escritas na MESMA transacao (este bloco e uma transacao), e o desfazer tem que
-- pegar a segunda. Com created_at o teste falha; com seq, passa.
do $$
declare cid bigint := 999999041; h uuid; r json; est numeric; st text;
begin
  delete from households where id in (select household_id from household_members where telegram_chat_id = cid);
  delete from household_members where telegram_chat_id = cid;
  perform mercado_create_family(cid, 'Casa Teste 0024', 'Tester');
  select household_id into h from household_members where telegram_chat_id = cid;

  perform mercado_apply(cid, 'vou_comprar', 'leite', null::text, 0, 5, 'l');  -- 1o evento
  perform mercado_apply(cid, 'tenho',       'leite', null::text, 0, 3, 'cx'); -- 2o evento, 0 -> 3

  assert (select count(distinct created_at) from mercado_events where household_id = h) >= 1,
    'sanidade: os dois eventos existem';

  r := mercado_desfazer(cid);
  assert r->>'desfeito' = 'estoque_ajustado',
    format('o desfazer tem que pegar a ULTIMA escrita, veio %s', r->>'desfeito');

  select current_stock into est from products where household_id = h and name = 'leite';
  assert est = 0, format('estoque do leite deveria ter voltado a 0, veio %s', est);

  select status into st from shopping_list where household_id = h and item_name = 'leite';
  assert st = 'pending', format('o item da lista NAO deveria ter sido tocado, veio %s', st);

  -- o segundo desfazer pega o evento de lista, que agora e o mais recente elegivel
  r := mercado_desfazer(cid);
  assert r->>'desfeito' = 'adicionado_lista',
    format('segundo desfazer deveria pegar a lista, veio %s', r->>'desfeito');
  select status into st from shopping_list where household_id = h and item_name = 'leite';
  assert st = 'removed', format('agora sim o item deveria estar removed, veio %s', st);

  -- seq e monotonica e nao repete
  assert (select count(*) = count(distinct seq) from mercado_events where household_id = h),
    'seq nao pode repetir';

  delete from households where id = h;
  delete from household_members where telegram_chat_id = cid;
  raise notice 'SELF-TEST 0024 (ordem do desfazer por seq) OK';
end $$;
